# Generated by Django 6.0.3 on 2026-03-19 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_main', models.ImageField(blank=True, help_text='Main hotel image', null=True, upload_to='hotels/')),
                ('image_room', models.ImageField(blank=True, help_text='Room view image', null=True, upload_to='hotels/rooms/')),
                ('map_3d_url', models.URLField(help_text='Google Maps 3D Embed Link', max_length=500)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('price', models.IntegerField(default=5000, help_text='Price per night in ₹')),
                ('location', models.CharField(default='India', max_length=255)),
                ('hotel_type', models.CharField(choices=[('leisure', 'Leisure'), ('business', 'Business'), ('honeymoon', 'Honeymoon'), ('family', 'Family')], default='leisure', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TicketBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_mode', models.CharField(default='airplane', max_length=50)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('travel_date', models.DateField()),
                ('passengers', models.IntegerField()),
                ('total_price', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('is_otp_verified', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, choices=[('UPI', 'UPI/Paytm'), ('CARD', 'Credit/Debit Card'), ('BANK', 'Net Banking')], max_length=10)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HotelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('stars', models.IntegerField(default=5)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.hotel')),
            ],
        ),
    ]
